<a href="https://colab.research.google.com/github/Mekondjo-EDSA/dsi_repo/blob/master/MA_forcasting_loading.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --upgrade --force-reinstall --no-deps kaggle

In [ ]:
#copy kaggle.json path and assign it to the environment 
import os 
os.environ['KAGGLE_CONFIG_DIR'] = '/content/drive/MyDrive/Kaggle'

In [ ]:
#change working directory to Kaggle folder containing json file
%cd /content/drive/MyDrive/Kaggle/

/content/drive/MyDrive/Kaggle

In [ ]:
#Download competition data
!kaggle competitions download -c ubiquant-market-prediction

Downloading ubiquant-market-prediction.zip to /content/drive/MyDrive/Kaggle
100% 7.49G/7.50G [01:16<00:00, 57.6MB/s]
100% 7.50G/7.50G [01:16<00:00, 106MB/s]

In [ ]:
%ls

kaggle.json  ubiquant-market-prediction.zip

In [ ]:
#unzip data 
import zipfile

for file in os.listdir():
    if file.endswith(".zip"):
        with zipfile.ZipFile(file, "r") as zip_file:
            zip_file.extractall()
        os.remove(file)

In [ ]:
%ls

example_sample_submission.csv  kaggle.json  ubiquant/
example_test.csv               train.csv

In [ ]:
#install dask 
!python -m pip install dask[dataframe] --upgrade

In [ ]:
!pip install memory_profiler

In [ ]:
#use dask to load dataframe 
import dask.dataframe as dd

ds = dd.read_csv('/content/drive/MyDrive/Kaggle/train.csv')

In [ ]:
#assess the dataframe as with pandas 
ds.head()

  row_id  time_id  investment_id  ...     f_297     f_298     f_299
0    0_1        0              1  ... -1.044826 -0.287605  0.321566
1    0_2        0              2  ... -0.929529 -0.974060 -0.343624
2    0_6        0              6  ... -0.612428 -0.113944  0.243608
3    0_7        0              7  ... -0.783423  1.151730 -0.773309
4    0_8        0              8  ...  0.753279  1.345611 -0.737624

[5 rows x 304 columns]

In [ ]:
ds.shape

(Delayed('int-b8145cac-a5b0-4645-b731-2bbaae34e605'), 304)

In [ ]:
ds.info()

<class 'dask.dataframe.core.DataFrame'>
Columns: 304 entries, row_id to f_299
dtypes: object(1), float64(301), int64(2)

In [1]:
#Loading data using pandas 
import pandas as pd

In [2]:
filename = '/content/drive/MyDrive/Kaggle/train.csv'

chunksize = 500000

chunk_df = pd.read_csv(filename, iterator=True, chunksize=chunksize)

In [3]:
df = pd.concat(chunk_df, ignore_index=True)

In [4]:
df.head()

  row_id  time_id  investment_id  ...     f_297     f_298     f_299
0    0_1        0              1  ... -1.044826 -0.287605  0.321566
1    0_2        0              2  ... -0.929529 -0.974060 -0.343624
2    0_6        0              6  ... -0.612428 -0.113944  0.243608
3    0_7        0              7  ... -0.783423  1.151730 -0.773309
4    0_8        0              8  ...  0.753279  1.345611 -0.737624

[5 rows x 304 columns]

In [5]:
df.shape

(3141410, 304)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3141410 entries, 0 to 3141409
Columns: 304 entries, row_id to f_299
dtypes: float64(301), int64(2), object(1)
memory usage: 7.1+ GB

In [7]:
df.isnull().sum()

row_id           0
time_id          0
investment_id    0
target           0
f_0              0
                ..
f_295            0
f_296            0
f_297            0
f_298            0
f_299            0
Length: 304, dtype: int64