In [1]:
#import 
import pandas as pd
import numpy as np
from google.colab import files

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
!pwd

/content

In [4]:
#change working directory
%cd /content/drive/MyDrive/dsi

/content/drive/MyDrive/dsi

In [5]:
#read tsv file into panda dataframe
akas_df = pd.read_csv('title.akas.tsv.gz', delimiter='\t', na_values=['\\N', 'NaN'] )

In [6]:
#rename titleId to tconst
akas_df = akas_df.rename(columns={'titleId':'tconst'})

In [7]:
akas_df.head()

      tconst  ordering  ... attributes isOriginalTitle
0  tt0000001         1  ...        NaN             0.0
1  tt0000001         2  ...        NaN             0.0
2  tt0000001         3  ...        NaN             0.0
3  tt0000001         4  ...        NaN             1.0
4  tt0000002         1  ...        NaN             1.0

[5 rows x 8 columns]

In [8]:
#Read in ratings tsv file
ratings_df = pd.read_csv('title.ratings.tsv.gz', delimiter='\t', na_values=['\\N', 'NaN'] )

In [9]:
ratings_df.head()

      tconst  averageRating  numVotes
0  tt0000001            5.8      1422
1  tt0000002            6.4       168
2  tt0000003            6.6      1015
3  tt0000004            6.4       100
4  tt0000005            6.2      1713

In [11]:
#Read in basics tsv 
basics_df = pd.read_csv('title.basics.tsv.gz', delimiter='\t', dtype={'runtimeMinutes': 'str'}, na_values=['\\N', 'NaN'] )

In [12]:
basics_df.head()

      tconst titleType  ... runtimeMinutes                    genres
0  tt0000001     short  ...              1         Documentary,Short
1  tt0000002     short  ...              5           Animation,Short
2  tt0000003     short  ...              4  Animation,Comedy,Romance
3  tt0000004     short  ...            NaN           Animation,Short
4  tt0000005     short  ...              1              Comedy,Short

[5 rows x 9 columns]

In [13]:
#check and drop dupliactes if any 
ratings_df.drop_duplicates()

           tconst  averageRating  numVotes
0       tt0000001            5.8      1422
1       tt0000002            6.4       168
2       tt0000003            6.6      1015
3       tt0000004            6.4       100
4       tt0000005            6.2      1713
...           ...            ...       ...
874198  tt9100972            7.0         5
874199  tt9104810            7.0         7
874200  tt9106766            7.6         5
874201  tt9107292            8.4        10
874202  tt9112162            9.9        10

[874203 rows x 3 columns]

In [14]:
#check and drop dupliates
basics_df.drop_duplicates()

            tconst  titleType  ... runtimeMinutes                    genres
0        tt0000001      short  ...              1         Documentary,Short
1        tt0000002      short  ...              5           Animation,Short
2        tt0000003      short  ...              4  Animation,Comedy,Romance
3        tt0000004      short  ...            NaN           Animation,Short
4        tt0000005      short  ...              1              Comedy,Short
...            ...        ...  ...            ...                       ...
5330271  tt9120652  tvEpisode  ...            NaN       Comedy,Drama,Family
5330272  tt9120654  tvEpisode  ...            NaN       Comedy,Drama,Family
5330273  tt9120656      short  ...             10              Horror,Short
5330274  tt9120782  videoGame  ...            NaN                       NaN
5330275  tt9120906  tvEpisode  ...            NaN       Comedy,Drama,Family

[5330276 rows x 9 columns]

In [15]:
#check and drop dupliactes
akas_df.drop_duplicates()

            tconst  ordering  ... attributes isOriginalTitle
0        tt0000001         1  ...        NaN             0.0
1        tt0000001         2  ...        NaN             0.0
2        tt0000001         3  ...        NaN             0.0
3        tt0000001         4  ...        NaN             1.0
4        tt0000002         1  ...        NaN             1.0
...            ...       ...  ...        ...             ...
3423655  tt9118622         2  ...        NaN             0.0
3423656  tt9118622         3  ...        NaN             1.0
3423657  tt9118622         4  ...        NaN             0.0
3423658  tt9118622         5  ...        NaN             0.0
3423659  tt9118622         6  ...        NaN             0.0

[3423660 rows x 8 columns]

In [16]:
merged_df = pd.merge(basics_df, ratings_df )

In [17]:
merged_df.head()

      tconst titleType  ... averageRating numVotes
0  tt0000001     short  ...           5.8     1422
1  tt0000002     short  ...           6.4      168
2  tt0000003     short  ...           6.6     1015
3  tt0000004     short  ...           6.4      100
4  tt0000005     short  ...           6.2     1713

[5 rows x 11 columns]

In [18]:
merged_df = pd.merge(merged_df, akas_df)

In [ ]:
merged_df.head()

      tconst titleType  ... averageRating numVotes
0  tt0000001     short  ...           5.8     1422
1  tt0000002     short  ...           6.4      168
2  tt0000003     short  ...           6.6     1015
3  tt0000004     short  ...           6.4      100
4  tt0000005     short  ...           6.2     1713

[5 rows x 11 columns]

In [19]:
merged_outer_df = pd.merge(pd.merge(basics_df, ratings_df, how = 'outer'), akas_df, how='outer')

In [20]:
merged_outer_df = pd.merge(merged_outer_df, akas_df, how='outer')

In [21]:
merged_outer_df.head()

      tconst titleType  ... attributes isOriginalTitle
0  tt0000001     short  ...        NaN             0.0
1  tt0000001     short  ...        NaN             0.0
2  tt0000001     short  ...        NaN             0.0
3  tt0000001     short  ...        NaN             1.0
4  tt0000002     short  ...        NaN             1.0

[5 rows x 18 columns]

In [22]:
print(merged_df.shape)
print(merged_outer_df.shape)

(1686547, 18)
(6740089, 18)

In [24]:
merged_df.titleType.unique()

array(['short', 'movie', 'tvMovie', 'tvSeries', 'tvEpisode', 'tvShort',
       'tvMiniSeries', 'tvSpecial', 'video', 'videoGame'], dtype=object)

In [27]:
merged_df.region.unique()

array(['HU', 'RU', 'US', nan, 'FR', 'RO', 'GB', 'PT', 'ES', 'UY', 'DE',
       'IT', 'FI', 'PL', 'AR', 'BR', 'XWW', 'TR', 'DK', 'XEU', 'SK', 'CZ',
       'SE', 'MX', 'GR', 'RS', 'XYU', 'AT', 'VE', 'CSHH', 'JP', 'AU',
       'NL', 'SI', 'NO', 'IR', 'UA', 'CA', 'CO', 'BG', 'BE', 'IN', 'DZ',
       'BF', 'XWG', 'NZ', 'VN', 'SUHH', 'EE', 'IS', 'DDDE', 'HR', 'CL',
       'LT', 'EG', 'GE', 'CH', 'PA', 'HK', 'CN', 'XSI', 'IE', 'XSA', 'PE',
       'IL', 'CU', 'KR', 'BA', 'BUMM', 'YUCS', 'XPI', 'BJ', 'PR', 'MY',
       'CM', 'AZ', 'ZA', 'TH', 'BO', 'DO', 'AL', 'EC', 'SG', 'LV', 'MA',
       'LI', 'LU', 'ID', 'PH', 'MZ', 'BM', 'PY', 'TW', 'JM', 'MD', 'LB',
       'TM', 'GL', 'MK', 'CR', 'TN', 'JO', 'KG', 'PK', 'LK', 'GT', 'XAS',
       'SN', 'TJ', 'NE', 'CI', 'MC', 'GH', 'TT', 'BS', 'SY', 'AO', 'KH',
       'GA', 'SV', 'MR', 'CY', 'ET', 'ML', 'NG', 'UZ', 'LY', 'SR', 'AM',
       'PG', 'IQ', 'BW', 'NI', 'ZM', 'CG', 'KZ', 'KP', 'XKO', 'GI', 'LA',
       'GW', 'BD', 'BY', 'ZW', 'MN', 'AF', 'TO', 'AW', 'BT', 'MT', 'GN',
       'TG', 'HN', 'TZ', 'KW', 'AD', 'NP', 'ZRCD', 'GY', 'CSXX', 'PS',
       'ER', 'SA', 'VDVN', 'SO', 'HT', 'IM', 'MU', 'BH', 'KE', 'GP', 'RW',
       'TD', 'XKV', 'CV', 'AE', 'SD', 'AG', 'NU', 'OM', 'CD', 'QA', 'BB',
       'MO', 'YE', 'LS', 'LC', 'ME', 'MV', 'BI', 'MH', 'VI', 'DM', 'SL',
       'XNA', 'BZ', 'FJ', 'MW', 'LR', 'SZ', 'UG', 'MG', 'AN', 'VU', 'GU',
       'MM', 'TV', 'FO', 'WS', 'SM', 'NC', 'BN', 'VA', 'GQ', 'TL', 'MQ',
       'GM', 'PW', 'PF', 'GD', 'CF', 'RE', 'SB'], dtype=object)

In [28]:
merged_df.language.unique()

array([nan, 'sv', 'en', 'tr', 'es', 'sr', 'cs', 'fa', 'fr', 'bg', 'ca',
       'nl', 'qbn', 'pt', 'ru', 'qbp', 'ar', 'rn', 'de', 'yi', 'uk', 'ka',
       'he', 'hr', 'sl', 'tg', 'sk', 'cmn', 'kk', 'da', 'el', 'fi', 'it',
       'gsw', 'pl', 'mr', 'qbo', 'gl', 'ms', 'th', 'ta', 'af', 'la', 'hy',
       'hi', 'ur', 'yue', 'te', 'bn', 'lt', 'mk', 'et', 'gd', 'tl', 'lv',
       'bs', 'cy', 'id', 'qal', 'goh', 'eu', 'ml', 'ro', 'hu', 'pa', 'uz',
       'ja', 'no', 'is', 'sq', 'vi', 'gu', 'nqo', 'kn', 'ga', 'xh', 'mi',
       'wo', 'ps', 'az', 'ky', 'fro', 'myv', 'ko', 'iu', 'st', 'zu', 'tn',
       'zh', 'ku'], dtype=object)

In [31]:
#filer out specified rows 
df_new = merged_df[((merged_df.language == 'en') | (merged_df.region == 'US')) & (merged_df.titleType == 'movie')]

In [36]:
df_new.head()

         tconst titleType  ... attributes isOriginalTitle
51    tt0000009     movie  ...        NaN             0.0
574   tt0000147     movie  ...        NaN             0.0
1446  tt0000630     movie  ...        NaN             0.0
1520  tt0000679     movie  ...        NaN             0.0
1797  tt0000886     movie  ...        NaN             0.0

[5 rows x 18 columns]

In [37]:
#create new column containing log10 values of the numVotes column
df_new['log10Votes'] = np.log10(df_new['numVotes'])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [38]:
df_new.head()

         tconst titleType  ... isOriginalTitle log10Votes
51    tt0000009     movie  ...             0.0   1.845098
574   tt0000147     movie  ...             0.0   2.424882
1446  tt0000630     movie  ...             0.0   1.000000
1520  tt0000679     movie  ...             0.0   1.414973
1797  tt0000886     movie  ...             0.0   1.204120

[5 rows x 19 columns]

In [39]:
#Lower the case of all text in the 'genres' column
df_new['genres'] = df_new['genres'].str.lower()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [40]:
df_new.head()

         tconst titleType  ... isOriginalTitle log10Votes
51    tt0000009     movie  ...             0.0   1.845098
574   tt0000147     movie  ...             0.0   2.424882
1446  tt0000630     movie  ...             0.0   1.000000
1520  tt0000679     movie  ...             0.0   1.414973
1797  tt0000886     movie  ...             0.0   1.204120

[5 rows x 19 columns]

In [48]:
df_new.groupby('genres', sort=False)['log10Votes'].mean().nlargest(10)

genres
action,fantasy,war            5.405722
action,family,romance         4.801753
animation,drama,war           4.396304
family,music,musical          4.396252
documentary,sport,thriller    4.386731
action,adventure,sci-fi       4.373261
horror,musical,sci-fi         4.340484
biography,fantasy,horror      4.271842
adventure,sci-fi,thriller     4.180897
adventure,drama,sci-fi        4.123983
Name: log10Votes, dtype: float64

In [47]:
df_new.groupby('genres', sort=False)['averageRating'].mean().nlargest(10)

genres
documentary,history,western        9.300000
history,sport                      9.200000
documentary,news,reality-tv        8.800000
animation,crime,documentary        8.525000
biography,history,music            8.500000
adventure,documentary,western      8.433333
documentary,drama,thriller         8.433333
comedy,mystery,sport               8.400000
biography,documentary,talk-show    8.300000
action,documentary,fantasy         8.300000
Name: averageRating, dtype: float64